"""
Script to visualize data files generated by smplx_to_robot.py using plots
This script loads and visualizes robot motion data that was saved in pickle format
by the smplx_to_robot.py script using line plots and other visualizations.
"""

import argparse
import os
import numpy as np
import pickle
from scipy.spatial.transform import Rotation as R
import matplotlib.pyplot as plt
from matplotlib import rcParams
from matplotlib.ticker import MaxNLocator

# Set matplotlib to support Chinese characters if needed
rcParams['font.sans-serif'] = ['SimHei', 'Arial', 'DejaVu Sans']
rcParams['axes.unicode_minus'] = False

def load_robot_motion_data(motion_file):
    """
    Load robot motion data from a pickle file.
    """
    with open(motion_file, "rb") as f:
        motion_data = pickle.load(f)
        motion_fps = motion_data["fps"]
        motion_root_pos = motion_data["root_pos"]
        motion_root_rot = motion_data["root_rot"]  # Note: saved as xyzw format in smplx_to_robot.py
        motion_dof_pos = motion_data["dof_pos"]
        motion_local_body_pos = motion_data["local_body_pos"]
        motion_link_body_list = motion_data["link_body_list"]
    return motion_data, motion_fps, motion_root_pos, motion_root_rot, motion_dof_pos, motion_local_body_pos, motion_link_body_list

def quaternion_to_euler(Quaternion):
    """
    Convert quaternion to Euler angles (roll, pitch, yaw)
    Quaternion: array of shape (n, 4) where each row is [x, y, z, w] format
    Returns: array of shape (n, 3) where each row is [roll, pitch, yaw] in radians
    """
    # Convert quaternion [x, y, z, w] to rotation object
    r = R.from_quat(Quaternion)
    # Convert to Euler angles in radians using xyz (roll, pitch, yaw) convention
    euler_angles = r.as_euler('xyz')
    return euler_angles

def plot_root_position(root_pos, fps, save_path=None):
    """
    Plot the root position (x, y, z) over time
    """
    time = np.arange(len(root_pos)) / fps
    
    fig, ax = plt.subplots(figsize=(12, 8))
    fig.suptitle('Root Position Over Time', fontsize=16)
    
    # X, Y, Z positions in one plot
    ax.plot(time, root_pos[:, 0], label='X Position', color='red')
    ax.plot(time, root_pos[:, 1], label='Y Position', color='green')
    ax.plot(time, root_pos[:, 2], label='Z Position', color='blue')
    
    ax.set_xlabel('Time (s)')
    ax.set_ylabel('Position (m)')
    ax.grid(True, alpha=0.3)
    ax.xaxis.set_major_locator(MaxNLocator(integer=True))
    ax.legend()
    
    plt.tight_layout()
    
    if save_path:
        plt.savefig(save_path.replace('.mp4', '_root_pos.png'), dpi=300, bbox_inches='tight')
    # plt.show() will be called later

def plot_root_rotation(root_rot, fps, save_path=None):
    """
    Plot the root rotation (roll, pitch, yaw) over time
    Note: root_rot is in xyzw format as saved by smplx_to_robot.py, convert to rpy
    """
    time = np.arange(len(root_rot)) / fps
    
    # Convert quaternion to Euler angles (roll, pitch, yaw)
    euler_angles = quaternion_to_euler(root_rot)
    
    fig, ax = plt.subplots(figsize=(12, 8))
    fig.suptitle('Root Rotation (Roll, Pitch, Yaw) Over Time', fontsize=16)
    
    # Roll, Pitch, Yaw in one plot
    ax.plot(time, euler_angles[:, 0], label='Roll', color='red')
    ax.plot(time, euler_angles[:, 1], label='Pitch', color='green')
    ax.plot(time, euler_angles[:, 2], label='Yaw', color='blue')
    
    ax.set_xlabel('Time (s)')
    ax.set_ylabel('Angle (rad)')
    ax.grid(True, alpha=0.3)
    ax.xaxis.set_major_locator(MaxNLocator(integer=True))
    ax.legend()
    
    plt.tight_layout()
    
    if save_path:
        plt.savefig(save_path.replace('.mp4', '_root_rot.png'), dpi=300, bbox_inches='tight')
    # plt.show() will be called later

def plot_dof_positions(dof_pos, fps, save_path=None, max_joints_to_plot=10):
    """
    Plot the DOF positions and velocities over time in separate figures for each joint
    """
    time = np.arange(len(dof_pos)) / fps
    n_dofs = dof_pos.shape[1]
    
    # Limit number of joints to plot to avoid overcrowding
    joints_to_plot = min(n_dofs, max_joints_to_plot)
    
    # Calculate velocities using numpy gradient
    dof_vel = np.gradient(dof_pos, axis=0) * fps  # Convert to rad/s
    
    # Create separate figures for each joint
    for i in range(joints_to_plot):
        fig, (ax_pos, ax_vel) = plt.subplots(2, 1, figsize=(12, 8))
        fig.suptitle(f'DOF {i} Position and Velocity Over Time', fontsize=16)
        
        # Plot position
        ax_pos.plot(time, dof_pos[:, i], label=f'DOF {i} Position', color='blue')
        ax_pos.set_ylabel('Position (rad)')
        ax_pos.grid(True, alpha=0.3)
        ax_pos.xaxis.set_major_locator(MaxNLocator(integer=True))
        ax_pos.legend()
        
        # Plot velocity
        ax_vel.plot(time, dof_vel[:, i], label=f'DOF {i} Velocity', color='red')
        ax_vel.set_xlabel('Time (s)')
        ax_vel.set_ylabel('Velocity (rad/s)')
        ax_vel.grid(True, alpha=0.3)
        ax_vel.xaxis.set_major_locator(MaxNLocator(integer=True))
        ax_vel.legend()
        
        plt.tight_layout()
        
        if save_path:
            plt.savefig(save_path.replace('.mp4', f'_dof_{i}_pos_vel.png'), dpi=300, bbox_inches='tight')
    # plt.show() will be called later

def plot_joint_statistics(dof_pos, save_path=None):
    """
    Plot statistics of joint positions (mean, std) across all timesteps
    """
    n_dofs = dof_pos.shape[1]
    
    # Calculate statistics
    mean_pos = np.mean(dof_pos, axis=0)
    std_pos = np.std(dof_pos, axis=0)
    min_pos = np.min(dof_pos, axis=0)
    max_pos = np.max(dof_pos, axis=0)
    
    fig, axes = plt.subplots(2, 2, figsize=(15, 10))
    fig.suptitle('Joint Position Statistics', fontsize=16)
    
    # Mean positions
    axes[0, 0].bar(range(n_dofs), mean_pos, color='skyblue', alpha=0.7)
    axes[0, 0].set_title('Mean Joint Position')
    axes[0, 0].set_xlabel('Joint Index')
    axes[0, 0].set_ylabel('Mean Position (rad)')
    axes[0, 0].grid(True, alpha=0.3)
    
    # Std positions
    axes[0, 1].bar(range(n_dofs), std_pos, color='lightcoral', alpha=0.7)
    axes[0, 1].set_title('Std Joint Position')
    axes[0, 1].set_xlabel('Joint Index')
    axes[0, 1].set_ylabel('Std Position (rad)')
    axes[0, 1].grid(True, alpha=0.3)
    
    # Min-Max range
    axes[1, 0].fill_between(range(n_dofs), min_pos, max_pos, alpha=0.3, color='lightgreen', label='Range')
    axes[1, 0].plot(range(n_dofs), mean_pos, color='green', label='Mean')
    axes[1, 0].set_title('Joint Position Range (Min-Max)')
    axes[1, 0].set_xlabel('Joint Index')
    axes[1, 0].set_ylabel('Position (rad)')
    axes[1, 0].grid(True, alpha=0.3)
    axes[1, 0].legend()
    
    # Joint movement range (max - min)
    range_pos = max_pos - min_pos
    axes[1, 1].bar(range(n_dofs), range_pos, color='gold', alpha=0.7)
    axes[1, 1].set_title('Joint Movement Range (Max - Min)')
    axes[1, 1].set_xlabel('Joint Index')
    axes[1, 1].set_ylabel('Movement Range (rad)')
    axes[1, 1].grid(True, alpha=0.3)
    
    plt.tight_layout()
    
    if save_path:
        plt.savefig(save_path.replace('.mp4', '_joint_stats.png'), dpi=300, bbox_inches='tight')
    # plt.show() will be called later

def visualize_robot_motion_plots(robot_motion_path, save_plots=False, output_dir="plots", max_joints_to_plot=10):
    """
    Visualize robot motion data using plots
    
    Args:
        robot_motion_path (str): Path to the pickle file containing robot motion data
        save_plots (bool): Whether to save the plots as image files
        output_dir (str): Directory to save plots if save_plots is True
        max_joints_to_plot (int): Maximum number of joints to plot in the DOF positions plot
    """
    
    if not os.path.exists(robot_motion_path):
        raise FileNotFoundError(f"Motion file {robot_motion_path} not found")
    
    # Load the robot motion data
    motion_data, motion_fps, motion_root_pos, motion_root_rot, motion_dof_pos, motion_local_body_pos, motion_link_body_list = load_robot_motion_data(robot_motion_path)
    
    print(f"Loaded motion data:")
    print(f"- FPS: {motion_fps}")
    print(f"- Total frames: {len(motion_root_pos)}")
    print(f"- Duration: {len(motion_root_pos) / motion_fps:.2f} seconds")
    print(f"- Root position shape: {motion_root_pos.shape}")
    print(f"- Root rotation shape: {motion_root_rot.shape}")
    print(f"- DOF positions shape: {motion_dof_pos.shape}")
    
    # Create output directory if saving plots
    if save_plots:
        os.makedirs(output_dir, exist_ok=True)
        base_filename = os.path.splitext(os.path.basename(robot_motion_path))[0]
        plot_save_path = os.path.join(output_dir, f"{base_filename}_motion_analysis.mp4")  # Using .mp4 extension as placeholder
    else:
        plot_save_path = None
    
    # Plot root position
    print("Plotting root position...")
    plot_root_position(motion_root_pos, motion_fps, plot_save_path)
    
    # Plot root rotation
    print("Plotting root rotation (converted to roll, pitch, yaw)...")
    plot_root_rotation(motion_root_rot, motion_fps, plot_save_path)
    
    # Plot DOF positions
    print("Plotting DOF positions and velocities for each joint...")
    plot_dof_positions(motion_dof_pos, motion_fps, plot_save_path, max_joints_to_plot)
    
    # Plot joint statistics
    print("Plotting joint statistics...")
    plot_joint_statistics(motion_dof_pos, plot_save_path)
    
    # Show all plots at once
    plt.show()
    print("Visualization complete!")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Visualize data files generated by smplx_to_robot.py using plots")
    parser.add_argument(
        "robot_motion_path", 
        type=str,
        help="Path to the pickle file containing robot motion data generated by smplx_to_robot.py"
    )
    parser.add_argument(
        "--save_plots", 
        action="store_true",
        help="Save the plots as image files"
    )
    parser.add_argument(
        "--output_dir", 
        type=str, 
        default="plots",
        help="Directory to save plots if save_plots is True"
    )
    parser.add_argument(
        "--max_joints_to_plot", 
        type=int, 
        default=10,
        help="Maximum number of joints to plot in the DOF positions plot (to avoid overcrowding)"
    )
    
    args = parser.parse_args()
    
    visualize_robot_motion_plots(
        robot_motion_path=args.robot_motion_path,
        save_plots=args.save_plots,
        output_dir=args.output_dir,
        max_joints_to_plot=args.max_joints_to_plot
    )